//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsCompleted { get; set; }
        public string Detail { get; set; }
        public string Priority { get; set; }
    }
}
